name: Start a run from Python file on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development
    path:
      - 'src/**'
    
jobs:
  run-files-in-development-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
        pip install kfp
        pip install scikit-learn
        
    - name: Connect to local server and run the Python files
      run: |       
        python src/submit_run.py
